version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: postgres
    ports:
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
